apiVersion: v1
kind: Pod
metadata:
  name: flask-webapp-healthcheck-test
  labels:
    name: flaskapp
spec:
  containers:
    - name: flask-webapp
      image: flask-webapp
      imagePullPolicy: Never
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
      ports:
        - containerPort: 5000
          hostPort: 5000
          name: app-port
      livenessProbe:
        httpGet:
          port: app-port
          path: /health
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 30
        failureThreshold: 3
